### PR TITLE
Fixes a bunch of dependency issues along with some code that had to c…

### PR DESCRIPTION
**Pull request by afred**
…hange

as a result.

* Pins ActiveFedora to ~> 8, the latest version that still uses Fedora 3.
  Updating to use ActiveFedora ~> 9.1 will require some work.
* Explicitly requires rspec matchers for equivalent-xml gem, which is required
  for compatibility with RSpec ~> 3.
* Updates more specs to RSpec ~> 3 syntax (still maybe not all).
* Updates datastreams in spec to have a dsid, as is now required by AF,
  and updates exemplar fixtures to include the dsid's specified in tests.
  NOTE: I'm not a fan of tight coupling between fixtures and tests.
* Fixes tests against .valid? checks on datastreams.

### CODE REVIEW

**Comment by afred** [comment]
**NOTE:** There are still 3 test failures due to issues with `logger` that _should_ be taken care of in #23. If we merge this PR (assuming only those 3 test failures), then I can rebase #23 and we _should_ have green tests

**Comment by awead** [comment]
@afred can you add the commit(s) from #23 to this PR and see if everything passes?

**Comment by afred** [comment]
already did :smile: travis is now churning...

**Comment by afred** [comment]
yay

**Comment by awead** [comment]
@afred you can remove the third commit and force push. We don't need a record of that merge because it'll be in the merge commit coming from this PR.

**Comment by afred** [comment]
@awead remove 593046509?

**Comment by awead** [comment]
no, https://github.com/WGBH/hydra-pbcore/commit/f65a445d8f995aed025cd93477a72e97382561e6
it's the same as https://github.com/WGBH/hydra-pbcore/commit/0149d715135b06a83abf7db0c78a342448cd20f9

**Comment by afred** [comment]
ah.. hmm... not sure how 0149d71 got in there. I thought it was still outstanding, and not yet in `master`. Ah well, squashed re-commit comming. Stand by...

**Comment by afred** [comment]
yay again.

**Pull request merged**
